import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./ui/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(() => { try { var t = localStorage.getItem('theme'); var d = t ? t === 'dark' : window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches; document.documentElement.setAttribute('data-theme', d ? 'dark' : 'light'); if(d) document.documentElement.classList.add('dark'); else document.documentElement.classList.remove('dark'); } catch(e) {} })();`,
          }}
        />
      </head>
      <body className={`antialiased`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
